In [3]:
string = "teste"
print(string[-1])

e


In [5]:
type(string)

str

In [8]:
lista = [1,2,3]
type(lista)

list

In [16]:
class Curso:
    def __init__(self, nome_curso, instrutores) -> None:
        self.nome_curso = nome_curso
        self.instrutores = instrutores
    
    def imprimir_instrutores(self):
        [print(professor) for professor in self.instrutores]


In [15]:
meu_curso = Curso("Python para iniciantes", ["Rodrigo", "Thiago"])
meu_curso.imprimir_instrutores()

Rodrigo
Thiago


In [17]:
m = lambda x: x * 2
print(m(10))

20


In [19]:
import numpy as np

In [23]:
l = [1,2,3,4,5]
print(l)
print(type(l))


[1, 2, 3, 4, 5]
<class 'list'>


In [24]:
l_np = np.array(l)
print(l_np)
print(type(l_np))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [25]:
a = [1,2,3]
b = [4,5,6]

In [26]:
np_a = np.array(a)
np_b = np.array(b)

In [27]:
a + b

[1, 2, 3, 4, 5, 6]

In [28]:
np_a + np_b

array([5, 7, 9])

In [29]:
np_a - np_b

array([-3, -3, -3])

In [30]:
np_a * np_b

array([ 4, 10, 18])

In [31]:
np_a / np_b

array([0.25, 0.4 , 0.5 ])

In [32]:
np_a * 2

array([2, 4, 6])

In [34]:
import pandas as pd
import numpy as np

In [38]:
df = pd.DataFrame(data=np.random.rand(5,4), index=['a', 'b', 'c', 'd', 'e'], columns=['w', 'x', 'y', 'z'])
print(df)

          w         x         y         z
a  0.932924  0.506640  0.587529  0.616101
b  0.090478  0.960881  0.027438  0.499747
c  0.520145  0.709509  0.938840  0.193708
d  0.323228  0.391319  0.112857  0.253039
e  0.030358  0.183546  0.006181  0.599372


In [37]:
df.to_numpy()

array([[0.57782814, 0.66557786, 0.20460635, 0.02181577],
       [0.89659931, 0.26536185, 0.97467777, 0.459481  ],
       [0.91799784, 0.69194975, 0.21899415, 0.29680129],
       [0.3487049 , 0.47755205, 0.9673888 , 0.93955621],
       [0.30477501, 0.85360009, 0.92043691, 0.53854375]])

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   w       5 non-null      float64
 1   x       5 non-null      float64
 2   y       5 non-null      float64
 3   z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [46]:
df.iat[0,0]

0.9329243277111693

AttributeError: module 'pandas' has no attribute 'to_csv'